apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tc-pipeline
spec:
  tasks:
    - name: npminstall
      taskRef:
        name: tc-tasks
    - name: tests
      taskRef:
        name: tc-tasks
    - name: build
      taskRef:
        name: tc-tasks
