apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tc-pipeline-run
spec:
  pipelineRef:
    name: tc-pipeline
  params:
    - name: pipeline-param
      value: "production"
  workspaces:
    - name: pipeline-shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
