apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tc-tasks
spec:
  steps:
    - name: npminstall
      image: node:16
      script: |
        npm install
    - name: jasmine-tests
      image: node:16
      script: |
        npx jasmine
